version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
          - dock

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dock
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    networks:
              - dock

volumes: 
   bundle_cache:

networks:
  dock:
