version: '3.7'
services:
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - .:/dock
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - sidekiq
    ports:
      - 3000:3000
    networks:
      - dock

  db:
    image: postgres:10.5
    env_file: .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - dock

  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - dock

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/dock
      - bundle_cache:/usr/local/bundle
    env_file: .env
    networks:
      - dock
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

volumes: 
  bundle_cache:
  redis_data:

networks:
  dock:
